[package]
name = "rustdoc-rag"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rustdoc-types = "0.32"
serde = "1.0"
serde_json = "1.0"
chromadb = "1.1"
ollama-rs = "0.2"
tokio = { version = "1.42", features = ["full"] }
